server:
  port: 8082

spring:
  application:
    name: otlmApp
  datasource:
    url: jdbc:postgresql://localhost:5432/jobsearchDB
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

management:
  otlp:
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
  metrics:
    distribution:
      percentiles-histogram:
        http_server_requests: true
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_TRACING_EXPORT_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  pattern:
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false