spring:
  application:
    name: otlmApp

management:
  metrics:
    distribution:
      percentiles-histogram:
        http_server_requests: true
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_TRACING_EXPORT_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  pattern:
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false